//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodsCollectorService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int Id { get; set; }
        public int GoodsID { get; set; }
        public string Client { get; set; }
        public int ManagerID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Manager Manager { get; set; }
    }
}
